#!/usr/bin/env python3
"""catcher.py - relay-room, BUILDER C: THE AGENT. One process per lane.

    python catcher.py --lane Fable          (alias: --as Fable)
    python catcher.py --lane Codex --once   (one pass, then exit - for the tripwires)

This is the mechanical half of the room. It does four things and nothing else:

  CATCH    watch state/room.md for `say` entries addressed to this lane whose flight trail
           lacks `caught`, oldest first, ONE per cycle - and verify the digest.
  HAND OFF write the immutable handoff envelope, then deliver the message into the
           QUARANTINED relay-gate instance by invoking gate.py as a subprocess with FP_COORD
           pointed at state/coord/ - a real sidecar, a real ACK cycle, a real MSG-… id.
  PUBLISH  rewrite state/status-<lane>.json EVERY cycle: heartbeat, the agent-layer state, the
           model-layer state read from the gate sidecar, and the in-flight stage.
  SURFACE  print exactly one line per signal, so a human or a model watching this terminal
           knows it has mail.

It is filesystem-only. It never speaks HTTP, takes no token and needs no server URL - so the
agent layer stays observable when the server is dead. That is deliberate (CONTRACT §4.8).

WHAT IT WILL NOT DO, and why (CONTRACT §4.8, the allow-list is `init post ticket status inbox`):

  gate.py check     - a read-shaped command that WRITES `state` (gate.py's `cmd_check`). Calling it on
                      a render tick would let the monitor change what it monitors.
  gate.py confirm   - a confirmation requires a RESTATEMENT, and a restatement generated by a
                      loop is a forged act of reading. Confirmation is model work.
  gate.py escalate  - reaches Rab. No agent goes to the principal.
  gate.py resolve   - records Rab's decision. No agent speaks for him.

  It also never writes stage `delivered` or `model-working`: only a model may say it has the
  message (CONTRACT §5.2). An agent asserting delivery on a model's behalf is the exact
  proxy-substitution defect docs/32 named - a mechanical signal standing in for a judgment.

  And it never writes the peer's sidecar: every gate call carries `--as <this lane>`, always.
  gate.py enforces this too (its `save()` refuses a foreign writer); this file does not
  work around it.

CRASH SAFETY. A torn or missing state file reads UNREAD and is republished - never silently
treated as idle (L1). The cycle body cannot raise out: any exception becomes `agent.state =
"error"` with a remedy, and the heartbeat keeps beating so the UI can tell "erroring" from
"gone" (they render differently, and must).
"""

import argparse
import io
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone

import roomlog
import status

PROTOCOL = status.PROTOCOL
LANES = status.LANES
GATE_TIMEOUT_S = 60.0
MIRROR_MAX_ATTEMPTS = 3

def tmp_dir():
    """state/tmp - scratch for gate.py --body files. A FUNCTION, not a module constant:
    roomlog.STATE is read at CALL time so the tripwires can relocate ROOT to a temp tree.
    A path frozen at import is a path a test cannot move, and an untestable guard is not
    a guard (L8)."""
    return roomlog.STATE / "tmp"

# The mirror note is the log's own record that a model->model entry reached the quarantined
# bus. It is machine-recoverable ON PURPOSE: if the journal is lost, the LOG is the witness
# and the catcher rebuilds from it rather than re-mirroring the whole history.
MIRROR_RE = re.compile(r"mirrored `(RM-[0-9a-f]{12})` into the quarantined relay as `([^`]+)`")
MSG_ID_RE = re.compile(r"\b(MSG-(?:FAB|CDX)-\d{4})\b")


def _read(path) -> str:
    """Read fully, then CLOSE. gate.py's `io.open(...).read()` idiom leaves the handle to the
    garbage collector; on Windows a lingering handle beside a lock directory is a defect
    waiting for a bad afternoon, and the tripwire run surfaced it as a ResourceWarning."""
    with io.open(path, encoding="utf-8", errors="replace") as fh:
        return fh.read()


def other_lane(lane):
    return LANES[1] if lane == LANES[0] else LANES[0]


def _atomic_json(path, doc):
    """.part then os.replace. assert_inside FIRST - nothing outside ROOT is written (L5)."""
    p = roomlog.assert_inside(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".part")
    with io.open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(json.dumps(doc, indent=2, ensure_ascii=False) + "\n")
    os.replace(tmp, p)
    return p


class Catcher:
    """One lane's agent. `one_cycle()` is the whole machine; the loop just repeats it."""

    def __init__(self, lane, interval=None, quiet=False, out=None):
        self.lane = status._lane(lane)
        self.peer = other_lane(self.lane)
        cfg, self.cfg_source = status.config()
        self.cfg = cfg
        self.interval = float(interval if interval is not None
                              else cfg.get("catcher_interval_s", 2.0))
        if self.interval <= 0:
            raise SystemExit("--interval must be > 0 seconds; the heartbeat IS the product.")
        self.quiet = quiet
        self.out = out if out is not None else sys.stdout

        # The document echoes the threshold it expects to be judged by (CONTRACT §4.7). A lane
        # running a deliberately slow loop must not be judged by the server's fast threshold -
        # and cannot exempt itself either, because out-of-range echoes render UNREAD (rule 8).
        stale = max(float(cfg.get("stale_after_s", 15.0)), self.interval * 7.5)
        self.stale_after_s = min(3600.0, max(1.0, round(stale, 3)))
        self.model_stale_after_s = float(cfg.get("model_stale_after_s", 300.0))
        self.declared_fresh_s = float(cfg.get("declared_fresh_s", 60.0))
        self.stall_after_s = float(cfg.get("flight_stall_after_s", 90.0))

        self.pid = os.getpid()
        self.started_utc = roomlog.utc_now()
        self.cycle_n = 0
        self.agent_state = "watching"
        self.agent_since = self.started_utc
        self.agent_detail = "starting"
        self.last_error = None
        self.consecutive_errors = 0
        self.gate_rec = None
        self.log_read = {"status": "UNREAD", "count": None, "torn": None, "debris": None,
                         "bytes": None, "read_utc": None,
                         "reason": "no cycle has run yet - this document was written at start-up"}
        self.in_flight = None
        self._model_seen = (None, None, self.started_utc)
        self._trail_seen = {}          # mid -> stage name last surfaced
        self.journal = None
        self.journal_status = "UNREAD"

    # ------------------------------------------------------------------ surfacing (d)

    def say(self, tag, text):
        """One clear line per signal. Never per idle cycle - a log that always prints tells you
        nothing when it prints."""
        if self.quiet:
            return
        stamp = datetime.now(timezone.utc).strftime("%H:%M:%SZ")
        try:
            print(f"[{stamp}] {self.lane:<6} {tag:<11} {text}", file=self.out, flush=True)
        except Exception:
            pass

    def banner(self):
        if self.quiet:
            return
        w = [f"relay-room catcher · lane {self.lane} · pid {self.pid} · started {self.started_utc}",
             f"  root      {roomlog.ROOT}",
             f"  log       {roomlog.ROOM_MD}",
             f"  coord     {roomlog.COORD}   (FP_COORD, forced on every gate.py call)",
             f"  gate      {roomlog.GATE_PY}",
             f"  handoff   {roomlog.HANDOFF_DIR / self.lane}   <- THIS IS THE MODEL'S INBOX",
             f"  status    {status.status_path(self.lane)}",
             f"  interval  {self.interval:g}s · stale_after {self.stale_after_s:g}s · "
             f"model_stale_after {self.model_stale_after_s:g}s · thresholds from {self.cfg_source}",
             "  QUARANTINE: the real coordination/ is NOT touched by this process.",
             "  allowed gate commands: init · post · ticket · status · inbox   "
             "(check/confirm/escalate/resolve are forbidden, permanently)",
             ""]
        for line in w:
            print(line, file=self.out, flush=True)

    # ------------------------------------------------------------------ start-up

    def start(self):
        for d in (roomlog.STATE, roomlog.COORD, roomlog.FLIGHT_DIR,
                  roomlog.HANDOFF_DIR / self.lane, tmp_dir()):
            roomlog.assert_inside(d).mkdir(parents=True, exist_ok=True)

        inherited = os.environ.get("FP_COORD")
        if inherited is not None:
            same = False
            try:
                same = os.path.realpath(inherited) == os.path.realpath(str(roomlog.COORD))
            except Exception:
                same = False
            if not same:
                shown = inherited if inherited else "(empty string)"
                self.say("QUARANTINE", f"inherited FP_COORD={shown} is OVERRIDDEN with "
                                       f"{roomlog.COORD}")
                self.note(
                    f"`catcher:{self.lane}` start-up: an inherited `FP_COORD` was found and "
                    f"OVERRIDDEN.\n\n"
                    f"- inherited: `{shown}`\n"
                    f"- forced to: `{roomlog.COORD}`\n\n"
                    f"Every `gate.py` subprocess from this process is launched with an "
                    f"explicitly constructed environment. gate.py's `coord_dir()` does a truthiness check, "
                    f"so an EMPTY inherited value would have fallen through to the real "
                    f"`coordination/` - where Rab has a live open escalation. It did not.")

        d, st, reason = status.read_sidecar(self.lane)
        if st != "ok" and not status.sidecar_path(self.lane).exists():
            # Missing is the one repairable case: `gate.py init` creates a REAL sidecar. A
            # MALFORMED one is never overwritten - it stays UNREAD until a human looks at it.
            self.say("GATE", f"no sidecar yet - running `gate.py init --as {self.lane}`")
            self.gate_init()
        elif st != "ok":
            self.say("UNREAD", reason)

    # ------------------------------------------------------------------ the journal

    def journal_path(self):
        return roomlog.STATE / f"handled-{self.lane.lower()}.json"

    def load_journal(self, log):
        """What this lane has already handled, so a restart does not re-deliver the log.

        AUTHORITY, stated so there are never two truths: the FLIGHT TRAIL is authoritative for
        `caught`/`handed` (CONTRACT §4.8 step 2 says so). The journal is authoritative for
        MIRRORS, which have no stage in the eight. A missing journal is a first run; an
        UNREADABLE one is UNREAD - it is republished from the log, never read as "nothing has
        been handled", because that would re-mirror the entire history.
        """
        p = self.journal_path()
        blank = {"protocol": PROTOCOL, "writer": f"catcher:{self.lane}", "lane": self.lane,
                 "updated_utc": roomlog.utc_now(), "caught": [], "mirrored": {},
                 "mirror_attempts": {}}
        if not p.exists():
            self.journal, self.journal_status = blank, "new"
            return
        try:
            d = json.loads(_read(p))
            if not isinstance(d, dict) or d.get("writer") != f"catcher:{self.lane}":
                raise ValueError(f"writer {(d or {}).get('writer')!r} is not "
                                 f"'catcher:{self.lane}'")
            for k, kind in (("caught", list), ("mirrored", dict), ("mirror_attempts", dict)):
                if not isinstance(d.get(k), kind):
                    raise ValueError(f"`{k}` is {type(d.get(k)).__name__}, expected "
                                     f"{kind.__name__}")
            self.journal, self.journal_status = d, "ok"
            return
        except Exception as exc:
            reason = (f"{status.rel(p)} is UNREAD ({type(exc).__name__}: "
                      f"{status.clip(exc, 90)}) - rebuilding it from {status.rel(roomlog.ROOM_MD)}, "
                      f"which is the witness that survives. No message is re-delivered.")
            self.say("UNREAD", reason)
            rebuilt = dict(blank)
            rebuilt["mirrored"] = self.mirrors_from_log(log)
            rebuilt["rebuilt_utc"] = roomlog.utc_now()
            rebuilt["rebuilt_reason"] = reason
            self.journal, self.journal_status = rebuilt, "REBUILT"
            self.save_journal()
            self.note(
                f"`catcher:{self.lane}` rebuilt its handled-journal from the log.\n\n"
                f"- reason: {reason}\n"
                f"- recovered mirrors: {len(rebuilt['mirrored'])}\n\n"
                f"A lost journal is not evidence that nothing was handled. The flight trails "
                f"under `state/flight/` remain authoritative for `caught` and `handed`.",
                kind="error")

    def mirrors_from_log(self, log):
        out = {}
        if getattr(log, "status", None) != "ok":
            return out
        for e in log.entries:
            if e.frm == self.lane and e.kind == "note":
                for mid, msg in MIRROR_RE.findall(e.body or ""):
                    out[mid] = msg
        return out

    def save_journal(self):
        try:
            self.journal["updated_utc"] = roomlog.utc_now()
            _atomic_json(self.journal_path(), self.journal)
        except Exception as exc:
            self.say("ERROR", f"could not write {status.rel(self.journal_path())}: {exc}")

    # ------------------------------------------------------------------ room entries

    def note(self, body, kind="note"):
        """An agent-authored mechanical note in the log's agent strip.

        `re_` is ALWAYS None. Stage 8 (`replied`) is derived from any entry whose `re:` names a
        message (CONTRACT §5.1) - so a note carrying `re:` would make a MECHANICAL line count
        as the MODEL'S REPLY. The id is named in the body text instead.
        """
        try:
            return roomlog.append_entry(frm=self.lane, to="all", body=body, re_=None, kind=kind)
        except Exception as exc:
            self.say("ERROR", f"could not append a `{kind}` entry ({type(exc).__name__}: "
                              f"{status.clip(exc, 120)}) - the log may be locked; check "
                              f"state/room.lock/")
            return None

    # ------------------------------------------------------------------ gate.py

    def gate_env(self):
        """FP_COORD is NEVER inherited: gate.py's `coord_dir()` is a truthiness check, so an empty inherited
        value falls through to the REAL coordination/. Constructed explicitly, every call."""
        return {**os.environ, "FP_COORD": str(roomlog.COORD)}

    def gate_record(self, proc):
        """Build the `gate` block. EXIT CODES ARE NOT HEALTH: `gate.py check` and `inbox` print
        `UNREAD: …` to stdout and exit 0. `gate.status` is therefore derived from PARSING THE
        SIDECAR (and from the UNREAD marker in the output), never from returncode. `last_rc` is
        recorded for display only. (T27 - SYM-031 in its exact local form.)

        Four statuses, and the distinction between the middle two is load-bearing:

          ok       the call landed.
          skipped  this agent declined to make the call (GUARD B).
          refused  gate.py REFUSED it, by one of its own laws (FULL STOP, GUARD A, GUARD B).
                   The bus is fine; a rule fired. Recorded verbatim, never retried, never
                   `--override`-d by an agent.
          UNREAD   the probe itself failed - gate.py could not be run, or the sidecar does not
                   read. This is the only one that means "I do not know".
        """
        out = (proc.stdout or "").strip()
        err = (proc.stderr or "").strip()
        _d, sidecar_st, sidecar_reason = status.read_sidecar(self.lane)
        st, reason = "ok", None
        if sidecar_st != "ok":
            st, reason = "UNREAD", sidecar_reason
        elif "UNREAD:" in out or "UNREAD:" in err:
            st = "UNREAD"
            reason = (f"gate.py printed `UNREAD:` and still exited {proc.returncode} - the exit "
                      f"code is not a health reading. Output: {status.clip(out or err, 200)}")
        elif proc.returncode != 0 and "REFUSED" in (err + out):
            st = "refused"
            reason = (f"gate.py REFUSED (rc {proc.returncode}): {status.clip(err or out, 400)}"
                      + ("  ← Rab's FULL STOP: only he lifts it, with `gate.py resolve`. No "
                         "agent may resolve, override or retry it."
                         if "FULL STOP" in (err + out) else
                         "  ← a gate law fired. The refusal is the record; nothing is retried."))
        elif proc.returncode != 0:
            st = "error"
            reason = (f"gate.py exited {proc.returncode}: {status.clip(err or out, 240)} - the "
                      f"sidecar still reads, so the bus is not broken. Read the message above.")
        rec = {
            "status": st,
            "reason": reason,
            "coord_dir": str(roomlog.COORD),
            "last_cmd": [str(x) for x in (proc.args or [])],
            "last_rc": proc.returncode,
            "last_utc": roomlog.utc_now(),
            "last_stdout": status.clip(out, 400) or None,
            "last_stderr": status.clip(err, 400) or None,
        }
        self.gate_rec = rec
        return rec

    def gate_failure(self, argv, exc):
        _d, sidecar_st, sidecar_reason = status.read_sidecar(self.lane)
        rec = {
            "status": "UNREAD",
            "reason": (f"gate.py could not be RUN ({type(exc).__name__}: "
                       f"{status.clip(exc, 120)}) - check that {roomlog.GATE_PY} exists and that "
                       f"{sys.executable} can execute it. Nothing was delivered."
                       + (f" Sidecar: {sidecar_reason}" if sidecar_st != "ok" else "")),
            "coord_dir": str(roomlog.COORD),
            "last_cmd": [str(x) for x in argv],
            "last_rc": None,
            "last_utc": roomlog.utc_now(),
            "last_stdout": None,
            "last_stderr": f"{type(exc).__name__}: {status.clip(exc, 240)}",
        }
        self.gate_rec = rec
        return rec

    # -- the three permitted invocations. The argv list literal sits AT the subprocess.run call
    # -- on purpose: T24 parses the source for list literals passed to subprocess.run and
    # -- asserts argv[2] - the subcommand - is in {init, post, ticket, status, inbox}.

    def gate_init(self):
        argv = [sys.executable, str(roomlog.GATE_PY), "init", "--as", self.lane]
        try:
            proc = subprocess.run(
                [sys.executable, str(roomlog.GATE_PY), "init", "--as", self.lane],
                capture_output=True, encoding="utf-8", errors="replace",
                env=self.gate_env(), cwd=str(roomlog.ROOT), timeout=GATE_TIMEOUT_S)
        except Exception as exc:
            return self.gate_failure(argv, exc)
        rec = self.gate_record(proc)
        self.say("GATE", f"init rc={rec['last_rc']} · {rec['last_stdout'] or rec['last_stderr']}")
        return rec

    def gate_ticket(self, mid):
        """Rab->model becomes a TICKET, not a post: gate.py's MODELS is ("Fable","Codex") - there
        is no Rab, and a catcher may not post as a party that does not exist."""
        argv = [sys.executable, str(roomlog.GATE_PY), "ticket", "--as", self.lane,
                "--id", mid, "--state", "working"]
        try:
            proc = subprocess.run(
                [sys.executable, str(roomlog.GATE_PY), "ticket", "--as", self.lane,
                 "--id", mid, "--state", "working"],
                capture_output=True, encoding="utf-8", errors="replace",
                env=self.gate_env(), cwd=str(roomlog.ROOT), timeout=GATE_TIMEOUT_S)
        except Exception as exc:
            return self.gate_failure(argv, exc)
        return self.gate_record(proc)

    def gate_post(self, body_path, subject):
        """Model->model is MIRRORED without --ticket. GUARD A (in gate.py's `cmd_post`) refuses a NEW ticket
        into a peer that is working; a mirror is a NOTICE, not an assignment, and a notice
        always passes. Acks stay ON - the discipline is real - and the catcher does NOT confirm
        them; the model does, in its own session. (T26 asserts no --ticket in this argv.)"""
        argv = [sys.executable, str(roomlog.GATE_PY), "post", "--as", self.lane,
                "--to", self.peer, "--subject", subject, "--body", str(body_path)]
        try:
            proc = subprocess.run(
                [sys.executable, str(roomlog.GATE_PY), "post", "--as", self.lane,
                 "--to", self.peer, "--subject", subject, "--body", str(body_path)],
                capture_output=True, encoding="utf-8", errors="replace",
                env=self.gate_env(), cwd=str(roomlog.ROOT), timeout=GATE_TIMEOUT_S)
        except Exception as exc:
            return self.gate_failure(argv, exc)
        return self.gate_record(proc)

    # ------------------------------------------------------------------ trails

    def trail_for(self, mid, log, now=None):
        """(whole trail object, this lane's sub-trail or None). render_trail is Builder A's; only
        its documented keys are touched (CONTRACT §5.4)."""
        try:
            t = roomlog.render_trail(mid, log, now=now, stall_after_s=self.stall_after_s)
        except Exception as exc:
            return None, None, f"{type(exc).__name__}: {status.clip(exc, 120)}"
        lane_t = ((t or {}).get("trails") or {}).get(self.lane)
        return t, lane_t, None

    @staticmethod
    def stage_map(lane_t):
        out = {}
        for s in ((lane_t or {}).get("stages") or []):
            if isinstance(s, dict) and s.get("name"):
                out[s["name"]] = s
        return out

    def reached(self, lane_t, stage):
        s = self.stage_map(lane_t).get(stage)
        return bool(s and s.get("reached"))

    # ------------------------------------------------------------------ the cycle

    def one_cycle(self, now=None):
        """One pass. Never raises: an exception becomes agent `error` + a remedy + a heartbeat."""
        self.cycle_n += 1
        try:
            self._cycle_body(now=now)
        except Exception as exc:
            self.consecutive_errors += 1
            self.last_error = (
                f"cycle {self.cycle_n} raised {type(exc).__name__}: {status.clip(exc, 200)} - the "
                f"agent is alive and still publishing, but it is NOT catching. Read this "
                f"terminal; if it repeats, stop the catcher and run "
                f"`python catcher.py --lane {self.lane} --once` to see the traceback.")
            self.set_agent("error", f"cycle {self.cycle_n} failed")
            self.say("ERROR", self.last_error)
        return self.publish()

    def set_agent(self, state, detail):
        if state != self.agent_state:
            self.agent_since = roomlog.utc_now()
        self.agent_state = state
        self.agent_detail = detail

    def _cycle_body(self, now=None):
        # 1 - read the log. An unreadable log is NEVER "no new messages".
        log = roomlog.read_log()
        self.log_read = {
            "status": log.status,
            "reason": log.reason,
            "count": len(log.entries) if log.status == "ok" else None,
            "torn": log.torn if log.status == "ok" else None,
            "debris": len(log.debris) if log.status == "ok" else None,
            "bytes": log.bytes if log.status == "ok" else None,
            "read_utc": log.read_utc,
        }
        if log.status != "ok":
            self.consecutive_errors += 1
            self.last_error = (log.reason or
                               f"{status.rel(roomlog.ROOM_MD)} read as {log.status} with no "
                               f"reason given - run `python room.py init`.")
            self.set_agent("error", f"the log read {log.status} - not catching")
            self.say("UNREAD", self.last_error)
            self.in_flight = None
            return

        self.consecutive_errors = 0
        self.last_error = None
        self.load_journal(log)

        # 2 - candidates: the CONVERSATION addressed to me, that I did not send.
        # kind is filtered to `say` on purpose: `note`/`error` are the agent strip (CONTRACT
        # §2.3). Ticketing a model over a lock-break note would be noise, and an `error` entry
        # addressed to `all` would make the agents catch each other's exhaust forever.
        inbound = [e for e in log.entries
                   if e.kind == "say" and e.frm != self.lane
                   and (e.to == self.lane or e.to == "all")]

        caught_one = None
        for e in inbound:
            _t, lane_t, err = self.trail_for(e.id, log, now=now)
            if err:
                self.say("ERROR", f"flight trail for {e.id} is UNREAD ({err})")
                continue
            if lane_t is None:
                # No sub-trail for my lane. Fall back to the journal so a strange reading can
                # never cause a RE-delivery; surface it either way.
                if e.id in (self.journal.get("caught") or []):
                    continue
            elif self.reached(lane_t, "caught"):
                self.surface_trail(e, lane_t)
                continue
            caught_one = e
            break

        if caught_one is not None:
            self.catch_and_hand(caught_one, log, now=now)
        else:
            mirrored = self.mirror_pass(log)
            if not mirrored:
                pending = "nothing in flight"
                self.set_agent(
                    "watching",
                    f"polling {status.rel(roomlog.ROOM_MD)} ({self.log_read['count']} entries, "
                    f"{self.log_read['bytes']} B) + {status.rel(status.sidecar_path(self.lane))} "
                    f"· {pending}")

        # 9 - the in-flight reading is recomputed from disk every cycle, not remembered.
        self.in_flight = self.compute_in_flight(log, now=now)

    # ------------------------------------------------------------------ catch + hand

    def catch_and_hand(self, entry, log, now=None):
        subj = roomlog.subject(entry.body, 80)
        self.set_agent("catching", f"reading {entry.id} from {entry.frm} and verifying its digest")
        self.publish()

        ok = bool(entry.digest_ok) and not entry.torn
        note = None
        if entry.torn:
            note = (f"the entry is TORN in {status.rel(roomlog.ROOM_MD)} (its terminator "
                    f"`<!-- /{entry.id} -->` is missing) - the body below the header may be "
                    f"incomplete. It is caught and shown, never merged and never dropped. "
                    f"Remedy: ask {entry.frm} to re-send; the torn bytes stay on the record.")
        elif not entry.digest_ok:
            note = (f"digest mismatch: {entry.digest_note or 'the header and the body disagree'} "
                    f"- the entry was edited after it was written. Remedy: treat the body as "
                    f"UNTRUSTED, ask {entry.frm} to re-send, and keep both records.")

        roomlog.append_stage(entry.id, "caught", f"catcher:{self.lane}", ok=ok, note=note)
        self.say("CAUGHT" if ok else "CAUGHT-RED",
                 f"{entry.id} from {entry.frm} · \"{subj}\"" + ("" if ok else f" · {note}"))

        if not ok:
            # A red trail must NEVER advance to `handed` (CONTRACT §5.4). Say so in the room.
            self.note(
                f"`catcher:{self.lane}` caught `{entry.id}` from **{entry.frm}** and the check "
                f"FAILED.\n\n- {note}\n\nThe trail stops at `caught` and is rendered RED. The "
                f"handoff envelope was not written and relay-gate was not called: nothing "
                f"downstream may render green above a failure.",
                kind="error")
            self.set_agent("watching", f"{entry.id} stopped at `caught` (red) - not handed")
            return

        # 4 - hand off. GUARD B first: read MY OWN sidecar before touching the gate.
        self.set_agent("handing", f"writing the handoff envelope for {entry.id} and calling "
                                  f"relay-gate")
        self.publish()

        side, side_st, side_reason = status.read_sidecar(self.lane)
        blocked = (side_st == "ok" and side.get("state") == "blocked-on-rab")
        if blocked:
            # GUARD B, carried across (S108/S109): a monitoring loop must never clear the
            # principal's gate as a side effect. That is exactly the defect S109 patched out of
            # `gate.py check`. The ticket call is SKIPPED ENTIRELY - not attempted, not forced.
            rec = {"status": "skipped", "reason":
                   (f"the {self.lane} sidecar reads `blocked-on-rab` - only Rab may clear it "
                    f"(gate.py has no path for a model to, and neither does this agent). The "
                    f"envelope is written and the message is in "
                    f"{status.rel(roomlog.HANDOFF_DIR / self.lane)}; the ticket was NOT set."),
                   "coord_dir": str(roomlog.COORD), "last_cmd": None, "last_rc": None,
                   "last_utc": roomlog.utc_now(), "last_stdout": None, "last_stderr": None}
            self.gate_rec = rec
            self.say("GUARD-B", f"{entry.id}: sidecar is blocked-on-rab - ticket NOT set; "
                                f"envelope written anyway")
            self.note(
                f"`catcher:{self.lane}` handed `{entry.id}` WITHOUT setting a relay-gate "
                f"ticket.\n\n"
                f"- sidecar state: `blocked-on-rab`\n"
                f"- what was skipped: `gate.py ticket --as {self.lane} --id {entry.id} "
                f"--state working`\n"
                f"- why: **only Rab may clear `blocked-on-rab`.** A monitoring loop that set a "
                f"ticket here would clear the principal's gate as a side effect - the S109 "
                f"defect, in a new file.\n"
                f"- the message is still deliverable: the envelope is in "
                f"`state/handoff/{self.lane}/{entry.id}.json` and the model may claim it.")
        else:
            if side_st != "ok":
                self.say("UNREAD", f"sidecar unread before the ticket call: {side_reason}")
            rec = self.gate_ticket(entry.id)
            line = rec.get("last_stdout") or rec.get("last_stderr") or ""
            st = rec.get("status")
            full_stop = "FULL STOP" in str(line)
            tag = {"ok": "HANDED", "refused": "FULL-STOP" if full_stop else "GATE-REFUSED"}.get(
                st, "HANDED-RED")
            self.say(tag, f"{entry.id} -> relay-gate ticket · rc={rec.get('last_rc')} · "
                          f"{status.clip(line, 200)}")
            if full_stop:
                self.note(
                    f"`catcher:{self.lane}` handed `{entry.id}` and relay-gate refused the "
                    f"ticket under **FULL STOP**.\n\n"
                    f"- rc `{rec.get('last_rc')}` · gate said:\n\n```\n"
                    f"{status.clip(line, 900)}\n```\n\n"
                    f"FULL STOP is Rab's rule (S109): an open escalation - or a lane that cannot "
                    f"be READ, because a lane that cannot be read cannot be shown clear of one - "
                    f"halts BOTH lanes. This agent does not retry it, does not `--override` it, "
                    f"and cannot `resolve` it: only Rab lifts a full stop.\n"
                    f"- the message is NOT lost: the envelope is in "
                    f"`state/handoff/{self.lane}/{entry.id}.json` and the model may claim it.\n"
                    f"- if the cause is an UNREAD peer lane, the fix is to start it: "
                    f"`python room.py init` (which runs `gate.py init` for BOTH lanes) then "
                    f"`python catcher.py --lane {self.peer}`.", kind="error")
            elif st == "refused":
                self.note(
                    f"`catcher:{self.lane}` handed `{entry.id}` and relay-gate REFUSED the "
                    f"ticket.\n\n- rc `{rec.get('last_rc')}` · gate said:\n\n```\n"
                    f"{status.clip(line, 900)}\n```\n\n"
                    f"A gate law fired. The refusal is the record; no agent retries or overrides "
                    f"one. The envelope is written and the model may still claim the message - "
                    f"but `gate.py status` will not show this lane holding a ticket.", kind="error")
            elif st != "ok":
                self.note(
                    f"`catcher:{self.lane}` called relay-gate for `{entry.id}` and the call did "
                    f"not read clean.\n\n"
                    f"- status: `{st}` · rc `{rec.get('last_rc')}`\n"
                    f"- reason: {rec.get('reason')}\n\n"
                    f"The envelope is written; the model can still claim the message. The "
                    f"relay-gate ticket is NOT set, so `gate.py status` will not show this "
                    f"lane working.", kind="error")

        self.write_envelope(entry, rec)
        # WHAT MAKES `handed` FAIL, decided rather than assumed. Stage 5 is "the envelope is
        # written AND the relay-gate call returned" (CONTRACT §5.1). A REFUSAL is a call that
        # returned - a gate law fired, on purpose, and the reason is on the record - so the
        # trail advances carrying the refusal as its note. Only a probe that FAILED (gate.py
        # could not be run, or the sidecar does not read) makes the stage red, because only
        # then is the state of the bus genuinely unknown. Rendering a correct halt as FAILED
        # would make Rab's own rule indistinguishable from a torn message.
        handed_ok = rec.get("status") in ("ok", "skipped", "refused")
        roomlog.append_stage(
            entry.id, "handed", f"catcher:{self.lane}", ok=handed_ok,
            note=(None if rec.get("status") == "ok" else rec.get("reason")))

        caught = self.journal.setdefault("caught", [])
        if entry.id not in caught:
            caught.append(entry.id)
        self.save_journal()

        # This process just DID this - so when the in-flight reading comes round in the same
        # cycle it is not a backlog it inherited, and must not be labelled one. The CAUGHT and
        # HANDED lines above are already the news.
        self._trail_seen[entry.id] = "handed"

        self.set_agent("awaiting-model",
                       (f"{entry.id} handed to {self.lane}; waiting for the MODEL to claim it "
                        f"(`python room.py claim --lane {self.lane} --id {entry.id}`) - only a "
                        f"model may write `delivered`")
                       if not blocked else
                       (f"sidecar is blocked-on-rab - only Rab may clear it; ticket not set. "
                        f"{entry.id} is in state/handoff/{self.lane}/ and can still be claimed"))

    def write_envelope(self, entry, gate_rec):
        """state/handoff/<Lane>/<mid>.json - WRITE-ONCE, never modified afterwards.

        Ordering note (the contract lists 'write envelope, then invoke the gate', but its own
        schema puts the gate RESULT inside the envelope): the gate is called first and the
        envelope is written once, complete, before the `handed` stage line. Whether the model
        has CLAIMED it is derived from the flight trail, never stored here - a second writer
        would give `claimed` two truths.
        """
        path = roomlog.HANDOFF_DIR / self.lane / f"{entry.id}.json"
        if path.exists():
            self.say("HANDOFF", f"{status.rel(path)} already exists - left untouched "
                                f"(write-once); the gate result of this run is in the status doc")
            return path, False
        doc = {
            "protocol": PROTOCOL, "writer": f"catcher:{self.lane}", "lane": self.lane,
            "id": entry.id, "utc": entry.utc, "from": entry.frm, "to": entry.to,
            "re": entry.re, "kind": entry.kind,
            "digest": entry.digest, "digest_ok": bool(entry.digest_ok),
            "digest_note": entry.digest_note, "torn": bool(entry.torn),
            "subject": roomlog.subject(entry.body, 80),
            "body": entry.body,
            "gate": gate_rec,
            "written_utc": roomlog.utc_now(),
        }
        _atomic_json(path, doc)
        return path, True

    # ------------------------------------------------------------------ mirroring

    def mirror_pass(self, log):
        """Model->model entries THIS lane wrote are pushed onto the quarantined bus, by the
        SENDER's lane, as a notice. Returns True when one was mirrored this cycle."""
        done = self.journal.get("mirrored") or {}
        attempts = self.journal.setdefault("mirror_attempts", {})
        for e in log.entries:
            if e.frm != self.lane or e.kind != "say" or e.to not in LANES or e.to == self.lane:
                continue
            if e.id in done:
                continue
            if int(attempts.get(e.id, 0)) >= MIRROR_MAX_ATTEMPTS:
                continue

            subj = roomlog.subject(e.body, 80)
            self.set_agent("mirroring", f"pushing {e.id} onto the quarantined relay bus")
            self.publish()
            attempts[e.id] = int(attempts.get(e.id, 0)) + 1

            try:
                tmp = roomlog.assert_inside(tmp_dir() / f"{e.id}.md")
                tmp.parent.mkdir(parents=True, exist_ok=True)
                with io.open(tmp, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(
                        f"**Mirrored from the room.** `{e.id}` · from `{e.frm}` → `{e.to}` · "
                        f"{e.utc}\n\n{e.body.strip()}\n\n"
                        f"---\n\n*Mirrored by `catcher:{self.lane}` out of "
                        f"`prototypes/relay-room/state/room.md`. The ACK is yours to give, in "
                        f"your own session: `gate.py confirm --as {e.to} --id <MSG-…> "
                        f"--restatement \"…\"`. No agent confirms on a model's behalf.*\n")
            except Exception as exc:
                self.say("ERROR", f"could not stage the mirror body for {e.id}: {exc}")
                self.save_journal()
                return True

            rec = self.gate_post(tmp, f"{e.id} {subj}")
            out = f"{rec.get('last_stdout') or ''} {rec.get('last_stderr') or ''}"
            m = MSG_ID_RE.search(out)
            msg_id = m.group(1) if m else None

            if rec.get("status") == "ok" and msg_id:
                done[e.id] = msg_id
                self.journal["mirrored"] = done
                self.save_journal()
                self.say("MIRRORED", f"{e.id} -> {self.peer} as {msg_id}")
                self.note(
                    f"`catcher:{self.lane}` mirrored `{e.id}` into the quarantined relay as "
                    f"`{msg_id}` (gate rc {rec.get('last_rc')}).\n\n"
                    f"- bus: `state/coord/relay.md` · sidecar: "
                    f"`state/coord/ack-{self.lane.lower()}.json`\n"
                    f"- posted WITHOUT `--ticket`: a mirror is a notice, not an assignment, and "
                    f"GUARD A refuses a new ticket into a peer that is working.\n"
                    f"- the ACK stays ON and belongs to **{self.peer}**, in its own session. No "
                    f"agent confirms for a model.")
                return True

            self.save_journal()
            left = MIRROR_MAX_ATTEMPTS - int(attempts.get(e.id, 0))
            reason = rec.get("reason") or "gate.py produced no MSG-… id"
            self.say("MIRROR-RED", f"{e.id} not mirrored ({reason}) · {left} attempt(s) left")
            if left <= 0:
                done[e.id] = "UNSENT-FAILED"
                self.journal["mirrored"] = done
                self.save_journal()
                self.note(
                    f"`catcher:{self.lane}` GAVE UP mirroring `{e.id}` after "
                    f"{MIRROR_MAX_ATTEMPTS} attempts.\n\n- last reason: {reason}\n"
                    f"- the room entry is intact and readable; only the copy on the "
                    f"relay-gate bus is missing.\n"
                    f"- remedy: fix the cause, then post it by hand — "
                    f"`gate.py post --as {self.lane} --to {self.peer} --subject \"{e.id} {subj}\" "
                    f"--body <file>` with `FP_COORD={roomlog.COORD}`.", kind="error")
            return True
        return False

    # ------------------------------------------------------------------ in flight

    def compute_in_flight(self, log, now=None):
        """The lane's current message, read fresh from disk every cycle. `null` here is a
        READING and is legal only because the flight dir just probed clean; when it does not,
        agent.state is `error` and last_error says so."""
        relevant = [e for e in log.entries
                    if e.kind == "say" and (
                        (e.frm != self.lane and (e.to == self.lane or e.to == "all"))
                        or (e.frm == self.lane and e.to in LANES))]
        for e in reversed(relevant):
            t, lane_t, err = self.trail_for(e.id, log, now=now)
            if err:
                self.consecutive_errors += 1
                self.last_error = (f"the flight trail for {e.id} could not be read ({err}) - "
                                   f"check state/flight/{e.id}.jsonl")
                self.set_agent("error", f"flight trail for {e.id} is UNREAD")
                return {"id": e.id, "from": e.frm, "subject": roomlog.subject(e.body, 80),
                        "stage": None, "stage_index": None, "stage_utc": None, "stage_by": None,
                        "age_s": None, "stalled": None, "rendered": "UNREAD", "reason":
                        self.last_error}
            if lane_t is None:
                continue
            idx = lane_t.get("stage_index")
            rendered = lane_t.get("rendered")
            if isinstance(idx, int) and idx >= 8 and rendered not in ("FAILED", "STALLED",
                                                                      "UNREAD"):
                continue                       # replied: complete, nothing in flight
            self.surface_trail(e, lane_t)
            return {
                "id": e.id, "from": e.frm, "subject": roomlog.subject(e.body, 80),
                "stage": lane_t.get("stage"), "stage_index": idx,
                "stage_utc": lane_t.get("stage_utc"), "stage_by": lane_t.get("stage_by"),
                "age_s": lane_t.get("age_s"),
                "stalled": rendered == "STALLED",
                "rendered": rendered, "reason": lane_t.get("reason"),
            }
        return None

    def surface_trail(self, entry, lane_t):
        """One line per NEW stage. The stages a model writes (`delivered`, `model-working`) are
        surfaced here too - this terminal is how a human sees the model answer the agent."""
        stage = (lane_t or {}).get("stage")
        if not stage or self._trail_seen.get(entry.id) == stage:
            return
        first = entry.id not in self._trail_seen
        idx = (lane_t or {}).get("stage_index")
        self._trail_seen[entry.id] = stage
        if first:
            # A start-up reading is not news - but it is not NOTHING either, and a --once run
            # is ALL start-up. gate.py's `watch` suppresses its first iteration silently, so
            # pre-existing state is never announced at all; that silence is a known wart the
            # contract calls out (§3.4). Here the backlog is printed and LABELLED as backlog,
            # which is the same information without the lie of omission.
            if isinstance(idx, int) and idx < 8:
                self.say("STANDING", f"{entry.id} · {stage} ({idx}/8) — already in this state "
                                     f"when this process started (backlog, not news)")
            return
        rendered = (lane_t or {}).get("rendered")
        tag = {"delivered": "DELIVERED", "model-working": "MODEL-WORKING",
               "replied": "REPLIED"}.get(stage, "STAGE")
        extra = "" if rendered in (None, stage) else f" [{rendered}]"
        self.say(tag, f"{entry.id} · {stage} ({lane_t.get('stage_index')}/8) by "
                      f"{lane_t.get('stage_by')}{extra}")

    # ------------------------------------------------------------------ model layer

    def model_block(self):
        """The model layer, read - never assumed. When the sidecar does not read, `state` is
        published as NULL: UNREAD is the reader's verdict, and a null renders UNREAD, never
        idle (CONTRACT §4.3/§4.4)."""
        sv = status.sidecar_view(self.lane)
        dv = status.declared_view(self.lane)
        state, source, note = None, None, None

        if sv["status"] == "ok":
            if sv["state"] in ("blocked-on-ack", "blocked-on-rab"):
                state, source = sv["state"], "sidecar"          # a declaration may not clear it
                note = (f"{sv['state']} comes from the relay-gate sidecar" +
                        (" - only Rab may clear it" if sv["state"] == "blocked-on-rab" else
                         " - waiting for the peer model to confirm"))
            elif (dv["status"] == "ok" and dv["state"] in status.MODEL_STATES
                  and dv["age_s"] is not None and dv["age_s"] <= self.declared_fresh_s):
                state, source, note = dv["state"], "declared", dv.get("note")
            else:
                state, source, note = sv["state"], "sidecar", sv.get("state_note")
        else:
            note = sv.get("reason")

        prev_state, prev_source, since = self._model_seen
        if (state, source) != (prev_state, prev_source):
            since = roomlog.utc_now()
            self._model_seen = (state, source, since)
            if state is not None:
                self.say("MODEL", f"{state} (from {source})"
                                  + (f" · {status.clip(note, 100)}" if note else ""))

        return {"state": state, "source": source, "since_utc": since,
                "note": status.clip(note, 300), "sidecar": sv, "declared": dv}

    # ------------------------------------------------------------------ publish (c)

    def publish(self):
        """The status document, rewritten EVERY cycle, unconditionally - even when nothing
        changed. The heartbeat IS the product: a document that stops moving is what makes L2
        (STALE, with an age) reachable at all."""
        doc = {
            "protocol": PROTOCOL,
            "writer": f"catcher:{self.lane}",
            "lane": self.lane,
            "pid": self.pid,
            "started_utc": self.started_utc,
            "heartbeat_utc": roomlog.utc_now(),
            "cycle": self.cycle_n,
            "heartbeat_interval_s": self.interval,
            "stale_after_s": self.stale_after_s,
            "model_stale_after_s": self.model_stale_after_s,
            "agent": {
                "state": self.agent_state,
                "since_utc": self.agent_since,
                "detail": self.agent_detail,
                "last_error": self.last_error,
                "consecutive_errors": self.consecutive_errors,
                "log_read": self.log_read,
                "journal": {"path": status.rel(self.journal_path()),
                            "status": self.journal_status,
                            "mirrored": len((self.journal or {}).get("mirrored") or {})},
            },
            "model": self.model_block(),
            "in_flight": self.in_flight,
            "gate": self.gate_rec or {
                "status": ("ok" if status.read_sidecar(self.lane)[1] == "ok" else "UNREAD"),
                "reason": status.read_sidecar(self.lane)[2],
                "coord_dir": str(roomlog.COORD), "last_cmd": None, "last_rc": None,
                "last_utc": None, "last_stdout": None,
                "last_stderr": None},
        }
        try:
            status.write_status(self.lane, doc)
        except Exception as exc:
            # The publish is the one thing that must not fail silently: if it does, the UI sees
            # a frozen heartbeat and renders STALE - correct, but the REASON would be lost.
            self.say("ERROR", f"could not publish {status.rel(status.status_path(self.lane))} "
                              f"({type(exc).__name__}: {status.clip(exc, 200)}) - the board will "
                              f"render this lane STALE within {self.stale_after_s:g}s, which is "
                              f"the honest reading. Fix the cause; do not delete the reader.")
        return doc

    # ------------------------------------------------------------------ the loop

    def run(self, once=False):
        self.banner()
        self.start()
        if once:
            doc = self.one_cycle()
            self.say("ONCE", f"cycle {self.cycle_n} complete · agent={doc['agent']['state']} "
                             f"· model={doc['model']['state']} · "
                             f"flight={(doc['in_flight'] or {}).get('stage')}")
            return doc
        self.say("START", f"watching every {self.interval:g}s · Ctrl+C to stop")
        try:
            while True:
                self.one_cycle()
                time.sleep(self.interval)
        except KeyboardInterrupt:
            self.say("STOP", f"stopped by hand. {status.rel(status.status_path(self.lane))} is "
                             f"left as it stands: it goes STALE in {self.stale_after_s:g}s and "
                             f"the board will say so with an age. Silence is not idleness.")
        return None


def main(argv=None):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass                        # gate.py's · — … come back as ? on the OEM codepage otherwise

    p = argparse.ArgumentParser(
        prog="catcher.py",
        description="relay-room: the gate relay agent for one lane (CONTRACT §4.8)")
    p.add_argument("--lane", "--as", dest="lane", required=True, choices=list(LANES),
                   help="the lane this process is the agent for. A lane is a SEAT, not a "
                        "model's name.")
    p.add_argument("--interval", type=float, default=None,
                   help="seconds between cycles (default: catcher_interval_s from "
                        "state/config.json)")
    p.add_argument("--once", action="store_true",
                   help="one pass, then exit - deterministic, no threads, no sleeps")
    p.add_argument("--quiet", action="store_true", help="publish, but print nothing")
    a = p.parse_args(argv)

    c = Catcher(a.lane, interval=a.interval, quiet=a.quiet)
    c.run(once=a.once)
    return 0


if __name__ == "__main__":
    sys.exit(main())
